apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: monolith
  namespace: cinemaabyss
spec:
  host: monolith
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: monolith
  namespace: cinemaabyss
spec:
  hosts:
    - monolith
  http:
    - route:
        - destination:
            host: monolith
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: movies-service
  namespace: cinemaabyss
spec:
  host: movies
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: movies-service
  namespace: cinemaabyss
spec:
  hosts:
    - movies
  http:
    - route:
        - destination:
            host: movies
            port:
              number: 8081
